language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby-9.0.0.0
  - rbx-2

matrix:
  allow_failures:
    - rvm: jruby-9.0.0.0
    - rvm: rbx-2

script: bundle exec rake

before_install:
  - gem update --system

services:
  - redis-server
